# Generated by Django 5.1.1 on 2025-12-31 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batas_minimal', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('karyawan', 'Karyawan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('status_2', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('datang', 'Barang Datang'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('tanggal_pesan', models.DateField(auto_now_add=True)),
                ('tanggal_datang', models.DateField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
    ]
