# Generated by Django 5.1.1 on 2026-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='batas_minimal',
        ),
        migrations.AddField(
            model_name='barang',
            name='batas_minimum',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
