# Generated by Django 5.1.1 on 2026-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_barang_batas_minimal_barang_batas_minimum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='batas_minimum',
        ),
        migrations.AddField(
            model_name='barang',
            name='batas_minimal',
            field=models.IntegerField(default=10),
        ),
    ]
