# Generated by Django 5.1.1 on 2026-01-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_barang_batas_minimum_barang_batas_minimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='jumlah_datang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
