# Generated by Django 5.1.1 on 2026-01-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pemesanan_jumlah_datang_pemesanan_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], max_length=10)),
                ('keterangan', models.TextField()),
                ('jumlah', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='batas_minimal',
            field=models.IntegerField(default=15),
        ),
    ]
