# Generated by Django 5.1.1 on 2026-02-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transaksikeuangan_alter_barang_batas_minimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('alasan', models.CharField(choices=[('rusak', 'Barang Rusak'), ('expired', 'Expired'), ('salah_kirim', 'Salah Kirim'), ('lainnya', 'Lainnya')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_retur', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
    ]
