# Generated by Django 5.1.1 on 2026-02-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_retur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='jumlah_rusak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
