# Generated by Django 5.1.1 on 2026-03-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_pemesanan_jumlah_rusak'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transaksipenjualan')),
            ],
        ),
    ]
