# Generated by Django 5.2.9 on 2026-04-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_transaksipenjualan_detailpenjualan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='kode_barang',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
